#配置yml文件
spring:
  profiles:
    active: prod


#配置分页
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

#配置 mybatis-plus
mybatis-plus:
  mapper-locations: classpath:/mappers/*.xml
  typeAliasesPackage: com.shop.entity
  global-config:
    db-config:
      select-strategy: not_empty
      insert-strategy: not_empty
      update-strategy: not_empty
      id-type: auto
  configuration:
    map-underscore-to-camel-case: true

#配置 mapper日志
logging:
  level:
    com.shop.mapper: debug
