#开发环境

#设置端口
server:
  port: 8085
#配置数据源
spring:
  datasource:
    url: jdbc:mysql://49.234.70.24:3306/shop?serverTimezone=GMT%2B8
    username: root
    password: a123456.
    driver-class-name: com.mysql.cj.jdbc.Driver

