server:
  port: 8085

spring:
  datasource:
    url: jdbc:mysql://49.234.70.24:3306/test?serverTimezone=GMT%2B8
    username: root
    password: a123456.
    driver-class-name: com.mysql.cj.jdbc.Driver
