#配置yml文件
spring:
  profiles:
    active: prod

#配置分页
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

#配置 mybatis xml
mybatis:
  mapper-locations: classpath:/mappers/*.xml
  type-aliases-package: com.shop.mapper

#配置 mapper日志
logging:
  level:
    com.shop.mapper: debug
