#开发环境

#设置端口
server:
  port: 8085

spring:
  # 配置数据源
  datasource:
    url: jdbc:mysql://49.234.70.24:3306/shop?serverTimezone=GMT%2B8
    username: root
    password: a123456.
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    platform: mysql
    #初始化大小，最小，最大
    initialSize: 5
    minIdle: 10
    maxActive: 20
    #配置获取连接等待超时的时间
    maxWait: 60000
    #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 2000
    #配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 600000
    #配置一个连接在池中最大生存的时间，单位是毫秒
    maxEvictableIdleTimeMillis: 900000
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    #打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

  rabbitmq:
    # 消息队列
    host: 49.234.70.24
    port: 5672
    username: test
    password: test
    virtual-host: /test
    listener:
      simple:
        prefetch: 1
        default-requeue-rejected: true
    publisher-returns: true
    template:
      mandatory: true

  # Redis数据库索引（默认为0）
  redis:
    database: 0
    host: 49.234.70.24
    port: 6379
    password:
    connect-timeout: 10000ms
    jedis:
      pool:
        max-active: 200
        max-wait: 1
        max-idle: 10
        min-idle: 0

  application:
    name: gabriel
nacos:
  config:
    server-addr: 49.234.70.24:8848

