/*
* 文 件 名:  BaseOrderDo.java
* 版     权:  靳旺商城版
* 描     述:  数据库实体类:BaseOrderDo
* 修 改 人:  Administrator
* 修改时间:  2020年12月04日
* 修改内容:  <修改内容>
*/
package com.shop.pojo;

import java.io.Serializable;
import java.util.Date;

public class BaseOrderDo implements Serializable {
    /**
     * 订单id
     */
    private Long pkBaseOrderId;

    /**
     * 商户id
     */
    private Long fkMerchantsId;

    /**
     * 客户id
     */
    private Long fkClientId;

    /**
     * 创建人
     */
    private Long createId;

    /**
     * 创建时间
     */
    private Date createTime;

    /**
     * 修改时间
     */
    private Date updateTime;

    /**
     * 假删除:n未删除y已删除
     */
    private String isDel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table base_order
     *
     * @mbggenerated Fri Dec 04 20:12:49 CST 2020
     */
    private static final long serialVersionUID = 1L;

    public Long getPkBaseOrderId() {
        return pkBaseOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_order.pk_base_order_id
     *
     * @param pkBaseOrderId the value for base_order.pk_base_order_id
     *
     * @mbggenerated Fri Dec 04 20:12:49 CST 2020
     */
    public void setPkBaseOrderId(Long pkBaseOrderId) {
        this.pkBaseOrderId = pkBaseOrderId;
    }

    public Long getFkMerchantsId() {
        return fkMerchantsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_order.fk_merchants_id
     *
     * @param fkMerchantsId the value for base_order.fk_merchants_id
     *
     * @mbggenerated Fri Dec 04 20:12:49 CST 2020
     */
    public void setFkMerchantsId(Long fkMerchantsId) {
        this.fkMerchantsId = fkMerchantsId;
    }

    public Long getFkClientId() {
        return fkClientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_order.fk_client_id
     *
     * @param fkClientId the value for base_order.fk_client_id
     *
     * @mbggenerated Fri Dec 04 20:12:49 CST 2020
     */
    public void setFkClientId(Long fkClientId) {
        this.fkClientId = fkClientId;
    }

    public Long getCreateId() {
        return createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_order.create_id
     *
     * @param createId the value for base_order.create_id
     *
     * @mbggenerated Fri Dec 04 20:12:49 CST 2020
     */
    public void setCreateId(Long createId) {
        this.createId = createId;
    }

    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_order.create_time
     *
     * @param createTime the value for base_order.create_time
     *
     * @mbggenerated Fri Dec 04 20:12:49 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_order.update_time
     *
     * @param updateTime the value for base_order.update_time
     *
     * @mbggenerated Fri Dec 04 20:12:49 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public String getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_order.is_del
     *
     * @param isDel the value for base_order.is_del
     *
     * @mbggenerated Fri Dec 04 20:12:49 CST 2020
     */
    public void setIsDel(String isDel) {
        this.isDel = isDel == null ? null : isDel.trim();
    }
}