/*
* 文 件 名:  ClassificationDo.java
* 版     权:  靳旺商城版
* 描     述:  数据库实体类:ClassificationDo
* 修 改 人:  Administrator
* 修改时间:  2020年12月04日
* 修改内容:  <修改内容>
*/
package com.shop.pojo;

import java.io.Serializable;
import java.util.Date;

public class ClassificationDo implements Serializable {
    /**
     * 商品类别id
     */
    private Long pkClassificationId;

    /**
     * 编号
     */
    private String classificationNo;

    /**
     * 名称
     */
    private String name;

    /**
     * 创建人
     */
    private Long createId;

    /**
     * 创建时间
     */
    private Date createTime;

    /**
     * 修改时间
     */
    private Date updateTime;

    /**
     * 假删除:n未删除y已删除
     */
    private String isDel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table classification
     *
     * @mbggenerated Fri Dec 04 20:12:49 CST 2020
     */
    private static final long serialVersionUID = 1L;

    public Long getPkClassificationId() {
        return pkClassificationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classification.pk_classification_id
     *
     * @param pkClassificationId the value for classification.pk_classification_id
     *
     * @mbggenerated Fri Dec 04 20:12:49 CST 2020
     */
    public void setPkClassificationId(Long pkClassificationId) {
        this.pkClassificationId = pkClassificationId;
    }

    public String getClassificationNo() {
        return classificationNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classification.classification_no
     *
     * @param classificationNo the value for classification.classification_no
     *
     * @mbggenerated Fri Dec 04 20:12:49 CST 2020
     */
    public void setClassificationNo(String classificationNo) {
        this.classificationNo = classificationNo == null ? null : classificationNo.trim();
    }

    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classification.name
     *
     * @param name the value for classification.name
     *
     * @mbggenerated Fri Dec 04 20:12:49 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    public Long getCreateId() {
        return createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classification.create_id
     *
     * @param createId the value for classification.create_id
     *
     * @mbggenerated Fri Dec 04 20:12:49 CST 2020
     */
    public void setCreateId(Long createId) {
        this.createId = createId;
    }

    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classification.create_time
     *
     * @param createTime the value for classification.create_time
     *
     * @mbggenerated Fri Dec 04 20:12:49 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classification.update_time
     *
     * @param updateTime the value for classification.update_time
     *
     * @mbggenerated Fri Dec 04 20:12:49 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public String getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classification.is_del
     *
     * @param isDel the value for classification.is_del
     *
     * @mbggenerated Fri Dec 04 20:12:49 CST 2020
     */
    public void setIsDel(String isDel) {
        this.isDel = isDel == null ? null : isDel.trim();
    }
}