/*
* 文 件 名:  ClientDo.java
* 版     权:  靳旺商城版
* 描     述:  数据库实体类:ClientDo
* 修 改 人:  Administrator
* 修改时间:  2020年12月04日
* 修改内容:  <修改内容>
*/
package com.shop.pojo;

import java.io.Serializable;
import java.util.Date;

public class ClientDo implements Serializable {
    /**
     * 客户id
     */
    private Long pkClientId;

    /**
     * 客户编号
     */
    private String clientNo;

    /**
     * 客户密码
     */
    private String password;

    /**
     * 账号
     */
    private String account;

    /**
     * 客户名称
     */
    private String clientName;

    /**
     * 客户电话
     */
    private String phone;

    /**
     * 头像
     */
    private String headPortrait;

    /**
     * 创建人
     */
    private Long createId;

    /**
     * 创建时间
     */
    private Date createTime;

    /**
     * 修改时间
     */
    private Date updateTime;

    /**
     * 假删除:n未删除y已删除
     */
    private String isDel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table client
     *
     * @mbggenerated Fri Dec 04 20:16:02 CST 2020
     */
    private static final long serialVersionUID = 1L;

    public Long getPkClientId() {
        return pkClientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.pk_client_id
     *
     * @param pkClientId the value for client.pk_client_id
     *
     * @mbggenerated Fri Dec 04 20:16:02 CST 2020
     */
    public void setPkClientId(Long pkClientId) {
        this.pkClientId = pkClientId;
    }

    public String getClientNo() {
        return clientNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.client_No
     *
     * @param clientNo the value for client.client_No
     *
     * @mbggenerated Fri Dec 04 20:16:02 CST 2020
     */
    public void setClientNo(String clientNo) {
        this.clientNo = clientNo == null ? null : clientNo.trim();
    }

    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.password
     *
     * @param password the value for client.password
     *
     * @mbggenerated Fri Dec 04 20:16:02 CST 2020
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.account
     *
     * @param account the value for client.account
     *
     * @mbggenerated Fri Dec 04 20:16:02 CST 2020
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    public String getClientName() {
        return clientName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.client_name
     *
     * @param clientName the value for client.client_name
     *
     * @mbggenerated Fri Dec 04 20:16:02 CST 2020
     */
    public void setClientName(String clientName) {
        this.clientName = clientName == null ? null : clientName.trim();
    }

    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.phone
     *
     * @param phone the value for client.phone
     *
     * @mbggenerated Fri Dec 04 20:16:02 CST 2020
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    public String getHeadPortrait() {
        return headPortrait;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.head_portrait
     *
     * @param headPortrait the value for client.head_portrait
     *
     * @mbggenerated Fri Dec 04 20:16:02 CST 2020
     */
    public void setHeadPortrait(String headPortrait) {
        this.headPortrait = headPortrait == null ? null : headPortrait.trim();
    }

    public Long getCreateId() {
        return createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.create_id
     *
     * @param createId the value for client.create_id
     *
     * @mbggenerated Fri Dec 04 20:16:02 CST 2020
     */
    public void setCreateId(Long createId) {
        this.createId = createId;
    }

    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.create_time
     *
     * @param createTime the value for client.create_time
     *
     * @mbggenerated Fri Dec 04 20:16:02 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.update_time
     *
     * @param updateTime the value for client.update_time
     *
     * @mbggenerated Fri Dec 04 20:16:02 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public String getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.is_del
     *
     * @param isDel the value for client.is_del
     *
     * @mbggenerated Fri Dec 04 20:16:02 CST 2020
     */
    public void setIsDel(String isDel) {
        this.isDel = isDel == null ? null : isDel.trim();
    }
}