/*
* 文 件 名:  CommodityColorDo.java
* 版     权:  靳旺商城版
* 描     述:  数据库实体类:CommodityColorDo
* 修 改 人:  Administrator
* 修改时间:  2020年12月04日
* 修改内容:  <修改内容>
*/
package com.shop.pojo;

import java.io.Serializable;
import java.util.Date;

public class CommodityColorDo implements Serializable {
    /**
     * 商品颜色分类表id
     */
    private Long pkCommodityColorId;

    /**
     * 颜色编号
     */
    private String commodityColorNo;

    /**
     * 颜色名称
     */
    private String name;

    /**
     * 创建人
     */
    private Long createId;

    /**
     * 创建时间
     */
    private Date createTime;

    /**
     * 修改时间
     */
    private Date updateTime;

    /**
     * 假删除:n未删除y已删除
     */
    private String isDel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table commodity_color
     *
     * @mbggenerated Fri Dec 04 20:12:49 CST 2020
     */
    private static final long serialVersionUID = 1L;

    public Long getPkCommodityColorId() {
        return pkCommodityColorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity_color.pk_commodity_color_id
     *
     * @param pkCommodityColorId the value for commodity_color.pk_commodity_color_id
     *
     * @mbggenerated Fri Dec 04 20:12:49 CST 2020
     */
    public void setPkCommodityColorId(Long pkCommodityColorId) {
        this.pkCommodityColorId = pkCommodityColorId;
    }

    public String getCommodityColorNo() {
        return commodityColorNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity_color.commodity_color_no
     *
     * @param commodityColorNo the value for commodity_color.commodity_color_no
     *
     * @mbggenerated Fri Dec 04 20:12:49 CST 2020
     */
    public void setCommodityColorNo(String commodityColorNo) {
        this.commodityColorNo = commodityColorNo == null ? null : commodityColorNo.trim();
    }

    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity_color.name
     *
     * @param name the value for commodity_color.name
     *
     * @mbggenerated Fri Dec 04 20:12:49 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    public Long getCreateId() {
        return createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity_color.create_id
     *
     * @param createId the value for commodity_color.create_id
     *
     * @mbggenerated Fri Dec 04 20:12:49 CST 2020
     */
    public void setCreateId(Long createId) {
        this.createId = createId;
    }

    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity_color.create_time
     *
     * @param createTime the value for commodity_color.create_time
     *
     * @mbggenerated Fri Dec 04 20:12:49 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity_color.update_time
     *
     * @param updateTime the value for commodity_color.update_time
     *
     * @mbggenerated Fri Dec 04 20:12:49 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public String getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity_color.is_del
     *
     * @param isDel the value for commodity_color.is_del
     *
     * @mbggenerated Fri Dec 04 20:12:49 CST 2020
     */
    public void setIsDel(String isDel) {
        this.isDel = isDel == null ? null : isDel.trim();
    }
}