/*
* 文 件 名:  CommodityDo.java
* 版     权:  靳旺商城版
* 描     述:  数据库实体类:CommodityDo
* 修 改 人:  Administrator
* 修改时间:  2020年12月04日
* 修改内容:  <修改内容>
*/
package com.shop.pojo;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class CommodityDo implements Serializable {
    /**
     * 商品表id
     */
    private Long pkCommodityId;

    /**
     * 商品编号
     */
    private String commodityNo;

    /**
     * 商品名称
     */
    private String commodityName;

    /**
     * 商品标题
     */
    private String title;

    /**
     * 是否采取促销价格：n：未采用促销价格，y：已采取促销价格
     */
    private String isPromotion;

    /**
     * 价格
     */
    private BigDecimal price;

    /**
     * 促销价格
     */
    private String promotionPrice;

    /**
     * 销量
     */
    private Long volume;

    /**
     * 累计评价
     */
    private String evaluate;

    /**
     * 尺寸
     */
    private String size;

    /**
     * 主级行业id
     */
    private Long fkIndustryId;

    /**
     * 次级行业id
     */
    private Long fkSecondaryIndustryId;

    /**
     * 商品类别id
     */
    private Long fkClassificationId;

    /**
     * 可送积分
     */
    private Long integral;

    /**
     * 创建人
     */
    private Long createId;

    /**
     * 创建时间
     */
    private Date createTime;

    /**
     * 修改时间
     */
    private Date updateTime;

    /**
     * 假删除:n未删除y已删除
     */
    private String isDel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table commodity
     *
     * @mbggenerated Fri Dec 04 20:12:49 CST 2020
     */
    private static final long serialVersionUID = 1L;

    public Long getPkCommodityId() {
        return pkCommodityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.pk_commodity_id
     *
     * @param pkCommodityId the value for commodity.pk_commodity_id
     *
     * @mbggenerated Fri Dec 04 20:12:49 CST 2020
     */
    public void setPkCommodityId(Long pkCommodityId) {
        this.pkCommodityId = pkCommodityId;
    }

    public String getCommodityNo() {
        return commodityNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.commodity_no
     *
     * @param commodityNo the value for commodity.commodity_no
     *
     * @mbggenerated Fri Dec 04 20:12:49 CST 2020
     */
    public void setCommodityNo(String commodityNo) {
        this.commodityNo = commodityNo == null ? null : commodityNo.trim();
    }

    public String getCommodityName() {
        return commodityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.commodity_name
     *
     * @param commodityName the value for commodity.commodity_name
     *
     * @mbggenerated Fri Dec 04 20:12:49 CST 2020
     */
    public void setCommodityName(String commodityName) {
        this.commodityName = commodityName == null ? null : commodityName.trim();
    }

    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.title
     *
     * @param title the value for commodity.title
     *
     * @mbggenerated Fri Dec 04 20:12:49 CST 2020
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    public String getIsPromotion() {
        return isPromotion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.is_promotion
     *
     * @param isPromotion the value for commodity.is_promotion
     *
     * @mbggenerated Fri Dec 04 20:12:49 CST 2020
     */
    public void setIsPromotion(String isPromotion) {
        this.isPromotion = isPromotion == null ? null : isPromotion.trim();
    }

    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.price
     *
     * @param price the value for commodity.price
     *
     * @mbggenerated Fri Dec 04 20:12:49 CST 2020
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    public String getPromotionPrice() {
        return promotionPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.promotion_price
     *
     * @param promotionPrice the value for commodity.promotion_price
     *
     * @mbggenerated Fri Dec 04 20:12:49 CST 2020
     */
    public void setPromotionPrice(String promotionPrice) {
        this.promotionPrice = promotionPrice == null ? null : promotionPrice.trim();
    }

    public Long getVolume() {
        return volume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.volume
     *
     * @param volume the value for commodity.volume
     *
     * @mbggenerated Fri Dec 04 20:12:49 CST 2020
     */
    public void setVolume(Long volume) {
        this.volume = volume;
    }

    public String getEvaluate() {
        return evaluate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.evaluate
     *
     * @param evaluate the value for commodity.evaluate
     *
     * @mbggenerated Fri Dec 04 20:12:49 CST 2020
     */
    public void setEvaluate(String evaluate) {
        this.evaluate = evaluate == null ? null : evaluate.trim();
    }

    public String getSize() {
        return size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.size
     *
     * @param size the value for commodity.size
     *
     * @mbggenerated Fri Dec 04 20:12:49 CST 2020
     */
    public void setSize(String size) {
        this.size = size == null ? null : size.trim();
    }

    public Long getFkIndustryId() {
        return fkIndustryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.fk_industry_id
     *
     * @param fkIndustryId the value for commodity.fk_industry_id
     *
     * @mbggenerated Fri Dec 04 20:12:49 CST 2020
     */
    public void setFkIndustryId(Long fkIndustryId) {
        this.fkIndustryId = fkIndustryId;
    }

    public Long getFkSecondaryIndustryId() {
        return fkSecondaryIndustryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.fk_secondary_industry_id
     *
     * @param fkSecondaryIndustryId the value for commodity.fk_secondary_industry_id
     *
     * @mbggenerated Fri Dec 04 20:12:49 CST 2020
     */
    public void setFkSecondaryIndustryId(Long fkSecondaryIndustryId) {
        this.fkSecondaryIndustryId = fkSecondaryIndustryId;
    }

    public Long getFkClassificationId() {
        return fkClassificationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.fk_classification_id
     *
     * @param fkClassificationId the value for commodity.fk_classification_id
     *
     * @mbggenerated Fri Dec 04 20:12:49 CST 2020
     */
    public void setFkClassificationId(Long fkClassificationId) {
        this.fkClassificationId = fkClassificationId;
    }

    public Long getIntegral() {
        return integral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.integral
     *
     * @param integral the value for commodity.integral
     *
     * @mbggenerated Fri Dec 04 20:12:49 CST 2020
     */
    public void setIntegral(Long integral) {
        this.integral = integral;
    }

    public Long getCreateId() {
        return createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.create_id
     *
     * @param createId the value for commodity.create_id
     *
     * @mbggenerated Fri Dec 04 20:12:49 CST 2020
     */
    public void setCreateId(Long createId) {
        this.createId = createId;
    }

    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.create_time
     *
     * @param createTime the value for commodity.create_time
     *
     * @mbggenerated Fri Dec 04 20:12:49 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.update_time
     *
     * @param updateTime the value for commodity.update_time
     *
     * @mbggenerated Fri Dec 04 20:12:49 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public String getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.is_del
     *
     * @param isDel the value for commodity.is_del
     *
     * @mbggenerated Fri Dec 04 20:12:49 CST 2020
     */
    public void setIsDel(String isDel) {
        this.isDel = isDel == null ? null : isDel.trim();
    }
}