/*
* 文 件 名:  ExpressDo.java
* 版     权:  靳旺商城版
* 描     述:  数据库实体类:ExpressDo
* 修 改 人:  Administrator
* 修改时间:  2020年12月04日
* 修改内容:  <修改内容>
*/
package com.shop.pojo;

import java.io.Serializable;
import java.util.Date;

public class ExpressDo implements Serializable {
    /**
     * 快递表id
     */
    private Long pkExpressId;

    /**
     * 快递编号
     */
    private String expressNo;

    /**
     * 快递名称
     */
    private String expressName;

    /**
     * 创建人
     */
    private Long createId;

    /**
     * 创建时间
     */
    private Date createTime;

    /**
     * 修改时间
     */
    private Date updateTime;

    /**
     * 假删除:n未删除y已删除
     */
    private String isDel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table express
     *
     * @mbggenerated Fri Dec 04 20:12:49 CST 2020
     */
    private static final long serialVersionUID = 1L;

    public Long getPkExpressId() {
        return pkExpressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column express.pk_express_id
     *
     * @param pkExpressId the value for express.pk_express_id
     *
     * @mbggenerated Fri Dec 04 20:12:49 CST 2020
     */
    public void setPkExpressId(Long pkExpressId) {
        this.pkExpressId = pkExpressId;
    }

    public String getExpressNo() {
        return expressNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column express.express_no
     *
     * @param expressNo the value for express.express_no
     *
     * @mbggenerated Fri Dec 04 20:12:49 CST 2020
     */
    public void setExpressNo(String expressNo) {
        this.expressNo = expressNo == null ? null : expressNo.trim();
    }

    public String getExpressName() {
        return expressName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column express.express_name
     *
     * @param expressName the value for express.express_name
     *
     * @mbggenerated Fri Dec 04 20:12:49 CST 2020
     */
    public void setExpressName(String expressName) {
        this.expressName = expressName == null ? null : expressName.trim();
    }

    public Long getCreateId() {
        return createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column express.create_id
     *
     * @param createId the value for express.create_id
     *
     * @mbggenerated Fri Dec 04 20:12:49 CST 2020
     */
    public void setCreateId(Long createId) {
        this.createId = createId;
    }

    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column express.create_time
     *
     * @param createTime the value for express.create_time
     *
     * @mbggenerated Fri Dec 04 20:12:49 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column express.update_time
     *
     * @param updateTime the value for express.update_time
     *
     * @mbggenerated Fri Dec 04 20:12:49 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public String getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column express.is_del
     *
     * @param isDel the value for express.is_del
     *
     * @mbggenerated Fri Dec 04 20:12:49 CST 2020
     */
    public void setIsDel(String isDel) {
        this.isDel = isDel == null ? null : isDel.trim();
    }
}