/*
* 文 件 名:  IndustryDo.java
* 版     权:  靳旺商城版
* 描     述:  数据库实体类:IndustryDo
* 修 改 人:  Administrator
* 修改时间:  2020年12月04日
* 修改内容:  <修改内容>
*/
package com.shop.pojo;

import java.io.Serializable;
import java.util.Date;

public class IndustryDo implements Serializable {
    /**
     * 行业表id
     */
    private Long pkIndustryId;

    /**
     * 行业编号
     */
    private String industryNo;

    /**
     * 行业名称
     */
    private String industryName;

    /**
     * 创建人
     */
    private Long createId;

    /**
     * 创建时间
     */
    private Date createTime;

    /**
     * 修改时间
     */
    private Date updateTime;

    /**
     * 假删除:n未删除y已删除
     */
    private String isDel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table industry
     *
     * @mbggenerated Fri Dec 04 20:12:49 CST 2020
     */
    private static final long serialVersionUID = 1L;

    public Long getPkIndustryId() {
        return pkIndustryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column industry.pk_industry_id
     *
     * @param pkIndustryId the value for industry.pk_industry_id
     *
     * @mbggenerated Fri Dec 04 20:12:49 CST 2020
     */
    public void setPkIndustryId(Long pkIndustryId) {
        this.pkIndustryId = pkIndustryId;
    }

    public String getIndustryNo() {
        return industryNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column industry.industry_no
     *
     * @param industryNo the value for industry.industry_no
     *
     * @mbggenerated Fri Dec 04 20:12:49 CST 2020
     */
    public void setIndustryNo(String industryNo) {
        this.industryNo = industryNo == null ? null : industryNo.trim();
    }

    public String getIndustryName() {
        return industryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column industry.industry_name
     *
     * @param industryName the value for industry.industry_name
     *
     * @mbggenerated Fri Dec 04 20:12:49 CST 2020
     */
    public void setIndustryName(String industryName) {
        this.industryName = industryName == null ? null : industryName.trim();
    }

    public Long getCreateId() {
        return createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column industry.create_id
     *
     * @param createId the value for industry.create_id
     *
     * @mbggenerated Fri Dec 04 20:12:49 CST 2020
     */
    public void setCreateId(Long createId) {
        this.createId = createId;
    }

    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column industry.create_time
     *
     * @param createTime the value for industry.create_time
     *
     * @mbggenerated Fri Dec 04 20:12:49 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column industry.update_time
     *
     * @param updateTime the value for industry.update_time
     *
     * @mbggenerated Fri Dec 04 20:12:49 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public String getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column industry.is_del
     *
     * @param isDel the value for industry.is_del
     *
     * @mbggenerated Fri Dec 04 20:12:49 CST 2020
     */
    public void setIsDel(String isDel) {
        this.isDel = isDel == null ? null : isDel.trim();
    }
}