/*
* 文 件 名:  IndustrySecondaryRelationDo.java
* 版     权:  靳旺商城版
* 描     述:  数据库实体类:IndustrySecondaryRelationDo
* 修 改 人:  Administrator
* 修改时间:  2020年12月04日
* 修改内容:  <修改内容>
*/
package com.shop.pojo;

import java.io.Serializable;
import java.util.Date;

public class IndustrySecondaryRelationDo implements Serializable {
    /**
     * 主次行业关联表id
     */
    private Long pkIndustrySecondaryRelationId;

    /**
     * 行业表id
     */
    private Long fkIndustryId;

    /**
     * 次级行业表id
     */
    private Long fkSecondaryIndustryId;

    /**
     * 商品类别
     */
    private Long fkClassificationId;

    /**
     * 创建人
     */
    private Long createId;

    /**
     * 创建时间
     */
    private Date createTime;

    /**
     * 修改时间
     */
    private Date updateTime;

    /**
     * 假删除:n未删除y已删除
     */
    private String isDel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table industry_secondary_relation
     *
     * @mbggenerated Fri Dec 04 20:12:49 CST 2020
     */
    private static final long serialVersionUID = 1L;

    public Long getPkIndustrySecondaryRelationId() {
        return pkIndustrySecondaryRelationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column industry_secondary_relation.pk_industry_secondary_relation_id
     *
     * @param pkIndustrySecondaryRelationId the value for industry_secondary_relation.pk_industry_secondary_relation_id
     *
     * @mbggenerated Fri Dec 04 20:12:49 CST 2020
     */
    public void setPkIndustrySecondaryRelationId(Long pkIndustrySecondaryRelationId) {
        this.pkIndustrySecondaryRelationId = pkIndustrySecondaryRelationId;
    }

    public Long getFkIndustryId() {
        return fkIndustryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column industry_secondary_relation.fk_industry_id
     *
     * @param fkIndustryId the value for industry_secondary_relation.fk_industry_id
     *
     * @mbggenerated Fri Dec 04 20:12:49 CST 2020
     */
    public void setFkIndustryId(Long fkIndustryId) {
        this.fkIndustryId = fkIndustryId;
    }

    public Long getFkSecondaryIndustryId() {
        return fkSecondaryIndustryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column industry_secondary_relation.fk_secondary_industry_id
     *
     * @param fkSecondaryIndustryId the value for industry_secondary_relation.fk_secondary_industry_id
     *
     * @mbggenerated Fri Dec 04 20:12:49 CST 2020
     */
    public void setFkSecondaryIndustryId(Long fkSecondaryIndustryId) {
        this.fkSecondaryIndustryId = fkSecondaryIndustryId;
    }

    public Long getFkClassificationId() {
        return fkClassificationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column industry_secondary_relation.fk_classification_id
     *
     * @param fkClassificationId the value for industry_secondary_relation.fk_classification_id
     *
     * @mbggenerated Fri Dec 04 20:12:49 CST 2020
     */
    public void setFkClassificationId(Long fkClassificationId) {
        this.fkClassificationId = fkClassificationId;
    }

    public Long getCreateId() {
        return createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column industry_secondary_relation.create_id
     *
     * @param createId the value for industry_secondary_relation.create_id
     *
     * @mbggenerated Fri Dec 04 20:12:49 CST 2020
     */
    public void setCreateId(Long createId) {
        this.createId = createId;
    }

    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column industry_secondary_relation.create_time
     *
     * @param createTime the value for industry_secondary_relation.create_time
     *
     * @mbggenerated Fri Dec 04 20:12:49 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column industry_secondary_relation.update_time
     *
     * @param updateTime the value for industry_secondary_relation.update_time
     *
     * @mbggenerated Fri Dec 04 20:12:49 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public String getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column industry_secondary_relation.is_del
     *
     * @param isDel the value for industry_secondary_relation.is_del
     *
     * @mbggenerated Fri Dec 04 20:12:49 CST 2020
     */
    public void setIsDel(String isDel) {
        this.isDel = isDel == null ? null : isDel.trim();
    }
}