/*
 * 文 件 名:  MerchantDo.java
 * 版     权:  靳旺商城版
 * 描     述:  数据库实体类:MerchantDo
 * 修 改 人:  Administrator
 * 修改时间:  2020年12月04日
 * 修改内容:  <修改内容>
 */
package com.shop.pojo;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class MerchantDo implements Serializable {
    /**
     * 商户表id
     */
    private Long pkMerchantsId;

    /**
     * 商户编号
     */
    private String merchantsNo;

    /**
     * 商户名称
     */
    private String name;

    /**
     * 客户id
     */
    private Long fkClientId;

    /**
     * 商户总资金
     */
    private BigDecimal money;

    /**
     * 已提现金额
     */
    private BigDecimal noWithdrawalMoney;

    /**
     * 可提现金额（已确认收货资金）
     */
    private BigDecimal cashAdvanceMoney;

    /**
     * 冻结金额（未确认收货资金）
     */
    private BigDecimal frozenMoney;

    /**
     * 商铺开户担保金额（资质）
     */
    private BigDecimal guaranteeMoney;

    /**
     * 卖家级别：merchantsLevel000：青铜卖家，merchants_level001：白银卖家，merchants_level002：黄金卖家，
     * merchants_level003：钻石卖家
     */
    private String merchantsLevel;

    /**
     * 店铺商品描述评分
     */
    private String descScore;

    /**
     * 店铺服务评分
     */
    private String serviceScore;

    /**
     * 店铺物流评分
     */
    private String logisticsScore;

    /**
     * 创建人
     */
    private Long createId;

    /**
     * 创建时间
     */
    private Date createTime;

    /**
     * 修改时间
     */
    private Date updateTime;

    /**
     * 假删除:n未删除y已删除
     */
    private String isDel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table merchant
     *
     * @mbggenerated Fri Dec 04 20:12:49 CST 2020
     */
    private static final long serialVersionUID = 1L;

    public Long getPkMerchantsId() {
        return pkMerchantsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant.pk_merchants_id
     *
     * @param pkMerchantsId the value for merchant.pk_merchants_id
     * @mbggenerated Fri Dec 04 20:12:49 CST 2020
     */
    public void setPkMerchantsId(Long pkMerchantsId) {
        this.pkMerchantsId = pkMerchantsId;
    }

    public String getMerchantsNo() {
        return merchantsNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant.merchants_no
     *
     * @param merchantsNo the value for merchant.merchants_no
     * @mbggenerated Fri Dec 04 20:12:49 CST 2020
     */
    public void setMerchantsNo(String merchantsNo) {
        this.merchantsNo = merchantsNo == null ? null : merchantsNo.trim();
    }

    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant.name
     *
     * @param name the value for merchant.name
     * @mbggenerated Fri Dec 04 20:12:49 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    public Long getFkClientId() {
        return fkClientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant.fk_client_id
     *
     * @param fkClientId the value for merchant.fk_client_id
     * @mbggenerated Fri Dec 04 20:12:49 CST 2020
     */
    public void setFkClientId(Long fkClientId) {
        this.fkClientId = fkClientId;
    }

    public BigDecimal getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant.money
     *
     * @param money the value for merchant.money
     * @mbggenerated Fri Dec 04 20:12:49 CST 2020
     */
    public void setMoney(BigDecimal money) {
        this.money = money;
    }

    public BigDecimal getNoWithdrawalMoney() {
        return noWithdrawalMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant.no_withdrawal_money
     *
     * @param noWithdrawalMoney
     * <p>
     *  the value for merchant.no_withdrawal_money
     * @mbggenerated Fri Dec 04 20:12:49 CST 2020
     */
    public void setNoWithdrawalMoney(BigDecimal noWithdrawalMoney) {
        this.noWithdrawalMoney = noWithdrawalMoney;
    }

    public BigDecimal getCashAdvanceMoney() {
        return cashAdvanceMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant.cash_advance_money
     *
     * @param cashAdvanceMoney the value for merchant.cash_advance_money
     * @mbggenerated Fri Dec 04 20:12:49 CST 2020
     */
    public void setCashAdvanceMoney(BigDecimal cashAdvanceMoney) {
        this.cashAdvanceMoney = cashAdvanceMoney;
    }

    public BigDecimal getFrozenMoney() {
        return frozenMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant.frozen_money
     *
     * @param frozenMoney the value for merchant.frozen_money
     * @mbggenerated Fri Dec 04 20:12:49 CST 2020
     */
    public void setFrozenMoney(BigDecimal frozenMoney) {
        this.frozenMoney = frozenMoney;
    }

    public BigDecimal getGuaranteeMoney() {
        return guaranteeMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant.guarantee
     * <p>
     * _money
     *
     * @param guaranteeMoney
     * <p>
     * Money the value for merchant.guarantee
     * <p>
     * _money
     * @mbggenerated Fri Dec 04 20:12:49 CST 2020
     */
    public void setGuaranteeMoney(BigDecimal guaranteeMoney) {
        this.guaranteeMoney = guaranteeMoney;
    }

    public String getMerchantsLevel() {
        return merchantsLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant.merchants_level
     *
     * @param merchantsLevel the value for merchant.merchants_level
     * @mbggenerated Fri Dec 04 20:12:49 CST 2020
     */
    public void setMerchantsLevel(String merchantsLevel) {
        this.merchantsLevel = merchantsLevel == null ? null : merchantsLevel.trim();
    }

    public String getDescScore() {
        return descScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant.desc_score
     *
     * @param descScore the value for merchant.desc_score
     * @mbggenerated Fri Dec 04 20:12:49 CST 2020
     */
    public void setDescScore(String descScore) {
        this.descScore = descScore == null ? null : descScore.trim();
    }

    public String getServiceScore() {
        return serviceScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant.service_score
     *
     * @param serviceScore the value for merchant.service_score
     * @mbggenerated Fri Dec 04 20:12:49 CST 2020
     */
    public void setServiceScore(String serviceScore) {
        this.serviceScore = serviceScore == null ? null : serviceScore.trim();
    }

    public String getLogisticsScore() {
        return logisticsScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant.logistics_score
     *
     * @param logisticsScore the value for merchant.logistics_score
     * @mbggenerated Fri Dec 04 20:12:49 CST 2020
     */
    public void setLogisticsScore(String logisticsScore) {
        this.logisticsScore = logisticsScore == null ? null : logisticsScore.trim();
    }

    public Long getCreateId() {
        return createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant.create_id
     *
     * @param createId the value for merchant.create_id
     * @mbggenerated Fri Dec 04 20:12:49 CST 2020
     */
    public void setCreateId(Long createId) {
        this.createId = createId;
    }

    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant.create_time
     *
     * @param createTime the value for merchant.create_time
     * @mbggenerated Fri Dec 04 20:12:49 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant.update_time
     *
     * @param updateTime the value for merchant.update_time
     * @mbggenerated Fri Dec 04 20:12:49 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public String getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant.is_del
     *
     * @param isDel the value for merchant.is_del
     * @mbggenerated Fri Dec 04 20:12:49 CST 2020
     */
    public void setIsDel(String isDel) {
        this.isDel = isDel == null ? null : isDel.trim();
    }
}