/*
* 文 件 名:  PartnerDo.java
* 版     权:  靳旺商城版
* 描     述:  数据库实体类:PartnerDo
* 修 改 人:  Administrator
* 修改时间:  2020年12月04日
* 修改内容:  <修改内容>
*/
package com.shop.pojo;

import java.io.Serializable;
import java.util.Date;

public class PartnerDo implements Serializable {
    /**
     * 合作商表id
     */
    private Long pkPartnerId;

    /**
     * 编号
     */
    private String partnerNo;

    /**
     * 名称
     */
    private String name;

    /**
     * 网页地址
     */
    private String address;

    /**
     * 创建人
     */
    private Long createId;

    /**
     * 创建时间
     */
    private Date createTime;

    /**
     * 修改时间
     */
    private Date updateTime;

    /**
     * 假删除:n未删除y已删除
     */
    private String isDel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table partner
     *
     * @mbggenerated Fri Dec 04 20:12:49 CST 2020
     */
    private static final long serialVersionUID = 1L;

    public Long getPkPartnerId() {
        return pkPartnerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner.pk_partner_id
     *
     * @param pkPartnerId the value for partner.pk_partner_id
     *
     * @mbggenerated Fri Dec 04 20:12:49 CST 2020
     */
    public void setPkPartnerId(Long pkPartnerId) {
        this.pkPartnerId = pkPartnerId;
    }

    public String getPartnerNo() {
        return partnerNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner.partner_no
     *
     * @param partnerNo the value for partner.partner_no
     *
     * @mbggenerated Fri Dec 04 20:12:49 CST 2020
     */
    public void setPartnerNo(String partnerNo) {
        this.partnerNo = partnerNo == null ? null : partnerNo.trim();
    }

    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner.name
     *
     * @param name the value for partner.name
     *
     * @mbggenerated Fri Dec 04 20:12:49 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner.address
     *
     * @param address the value for partner.address
     *
     * @mbggenerated Fri Dec 04 20:12:49 CST 2020
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    public Long getCreateId() {
        return createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner.create_id
     *
     * @param createId the value for partner.create_id
     *
     * @mbggenerated Fri Dec 04 20:12:49 CST 2020
     */
    public void setCreateId(Long createId) {
        this.createId = createId;
    }

    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner.create_time
     *
     * @param createTime the value for partner.create_time
     *
     * @mbggenerated Fri Dec 04 20:12:49 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner.update_time
     *
     * @param updateTime the value for partner.update_time
     *
     * @mbggenerated Fri Dec 04 20:12:49 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public String getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner.is_del
     *
     * @param isDel the value for partner.is_del
     *
     * @mbggenerated Fri Dec 04 20:12:49 CST 2020
     */
    public void setIsDel(String isDel) {
        this.isDel = isDel == null ? null : isDel.trim();
    }
}