/*
* 文 件 名:  RoleDo.java
* 版     权:  靳旺商城版
* 描     述:  数据库实体类:RoleDo
* 修 改 人:  Administrator
* 修改时间:  2020年12月05日
* 修改内容:  <修改内容>
*/
package com.shop.pojo;

import java.io.Serializable;
import java.util.Date;

public class RoleDo implements Serializable {
    /**
     * 角色id
     */
    private Long pkRoleId;

    /**
     * 编号
     */
    private String roleNo;

    /**
     * 名称
     */
    private String roleName;

    /**
     * 角色描述
     */
    private String roleDesc;

    /**
     * 创建人
     */
    private Long createId;

    /**
     * 创建时间
     */
    private Date createTime;

    /**
     * 修改时间
     */
    private Date updateTime;

    /**
     * 假删除:n未删除y已删除
     */
    private String isDel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table role
     *
     * @mbggenerated Sat Dec 05 18:39:23 CST 2020
     */
    private static final long serialVersionUID = 1L;

    public Long getPkRoleId() {
        return pkRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.pk_role_id
     *
     * @param pkRoleId the value for role.pk_role_id
     *
     * @mbggenerated Sat Dec 05 18:39:23 CST 2020
     */
    public void setPkRoleId(Long pkRoleId) {
        this.pkRoleId = pkRoleId;
    }

    public String getRoleNo() {
        return roleNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.role_no
     *
     * @param roleNo the value for role.role_no
     *
     * @mbggenerated Sat Dec 05 18:39:23 CST 2020
     */
    public void setRoleNo(String roleNo) {
        this.roleNo = roleNo == null ? null : roleNo.trim();
    }

    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.role_name
     *
     * @param roleName the value for role.role_name
     *
     * @mbggenerated Sat Dec 05 18:39:23 CST 2020
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    public String getRoleDesc() {
        return roleDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.role_desc
     *
     * @param roleDesc the value for role.role_desc
     *
     * @mbggenerated Sat Dec 05 18:39:23 CST 2020
     */
    public void setRoleDesc(String roleDesc) {
        this.roleDesc = roleDesc == null ? null : roleDesc.trim();
    }

    public Long getCreateId() {
        return createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.create_id
     *
     * @param createId the value for role.create_id
     *
     * @mbggenerated Sat Dec 05 18:39:23 CST 2020
     */
    public void setCreateId(Long createId) {
        this.createId = createId;
    }

    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.create_time
     *
     * @param createTime the value for role.create_time
     *
     * @mbggenerated Sat Dec 05 18:39:23 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.update_time
     *
     * @param updateTime the value for role.update_time
     *
     * @mbggenerated Sat Dec 05 18:39:23 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public String getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.is_del
     *
     * @param isDel the value for role.is_del
     *
     * @mbggenerated Sat Dec 05 18:39:23 CST 2020
     */
    public void setIsDel(String isDel) {
        this.isDel = isDel == null ? null : isDel.trim();
    }
}