/*
* 文 件 名:  SecondaryIndustryDo.java
* 版     权:  靳旺商城版
* 描     述:  数据库实体类:SecondaryIndustryDo
* 修 改 人:  Administrator
* 修改时间:  2020年12月04日
* 修改内容:  <修改内容>
*/
package com.shop.pojo;

import java.io.Serializable;
import java.util.Date;

public class SecondaryIndustryDo implements Serializable {
    /**
     * 次级行业表id
     */
    private Long pkSecondaryIndustryId;

    /**
     * 编号
     */
    private String secondaryIndustryNo;

    /**
     * 名称
     */
    private String name;

    /**
     * 创建人
     */
    private Long createId;

    /**
     * 创建时间
     */
    private Date createTime;

    /**
     * 修改时间
     */
    private Date updateTime;

    /**
     * 假删除:n未删除y已删除
     */
    private String isDel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table secondary_industry
     *
     * @mbggenerated Fri Dec 04 20:12:49 CST 2020
     */
    private static final long serialVersionUID = 1L;

    public Long getPkSecondaryIndustryId() {
        return pkSecondaryIndustryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column secondary_industry.pk_secondary_industry_id
     *
     * @param pkSecondaryIndustryId the value for secondary_industry.pk_secondary_industry_id
     *
     * @mbggenerated Fri Dec 04 20:12:49 CST 2020
     */
    public void setPkSecondaryIndustryId(Long pkSecondaryIndustryId) {
        this.pkSecondaryIndustryId = pkSecondaryIndustryId;
    }

    public String getSecondaryIndustryNo() {
        return secondaryIndustryNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column secondary_industry.secondary_industry_no
     *
     * @param secondaryIndustryNo the value for secondary_industry.secondary_industry_no
     *
     * @mbggenerated Fri Dec 04 20:12:49 CST 2020
     */
    public void setSecondaryIndustryNo(String secondaryIndustryNo) {
        this.secondaryIndustryNo = secondaryIndustryNo == null ? null : secondaryIndustryNo.trim();
    }

    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column secondary_industry.name
     *
     * @param name the value for secondary_industry.name
     *
     * @mbggenerated Fri Dec 04 20:12:49 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    public Long getCreateId() {
        return createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column secondary_industry.create_id
     *
     * @param createId the value for secondary_industry.create_id
     *
     * @mbggenerated Fri Dec 04 20:12:49 CST 2020
     */
    public void setCreateId(Long createId) {
        this.createId = createId;
    }

    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column secondary_industry.create_time
     *
     * @param createTime the value for secondary_industry.create_time
     *
     * @mbggenerated Fri Dec 04 20:12:49 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column secondary_industry.update_time
     *
     * @param updateTime the value for secondary_industry.update_time
     *
     * @mbggenerated Fri Dec 04 20:12:49 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public String getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column secondary_industry.is_del
     *
     * @param isDel the value for secondary_industry.is_del
     *
     * @mbggenerated Fri Dec 04 20:12:49 CST 2020
     */
    public void setIsDel(String isDel) {
        this.isDel = isDel == null ? null : isDel.trim();
    }
}