/*
* 文 件 名:  SystemParameterDo.java
* 版     权:  靳旺商城版
* 描     述:  数据库实体类:SystemParameterDo
* 修 改 人:  Administrator
* 修改时间:  2020年12月04日
* 修改内容:  <修改内容>
*/
package com.shop.pojo;

import java.io.Serializable;
import java.util.Date;

public class SystemParameterDo implements Serializable {
    /**
     * 系统枚举表id
     */
    private Long pkSystemEnumId;

    /**
     * 枚举编号
     */
    private Integer systemEnumNo;

    /**
     * 枚举常量
     */
    private Long constant;

    /**
     * 枚举key
     */
    private String key;

    /**
     * 枚举值
     */
    private String value;

    /**
     * 描述
     */
    private String desc;

    /**
     * 排序
     */
    private Long sort;

    /**
     * 创建人
     */
    private Long createId;

    /**
     * 创建时间
     */
    private Date createTime;

    /**
     * 修改时间
     */
    private Date updateTime;

    /**
     * 假删除:n未删除y已删除
     */
    private String isDel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table system_parameter
     *
     * @mbggenerated Fri Dec 04 20:12:49 CST 2020
     */
    private static final long serialVersionUID = 1L;

    public Long getPkSystemEnumId() {
        return pkSystemEnumId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_parameter.pk_system_enum_id
     *
     * @param pkSystemEnumId the value for system_parameter.pk_system_enum_id
     *
     * @mbggenerated Fri Dec 04 20:12:49 CST 2020
     */
    public void setPkSystemEnumId(Long pkSystemEnumId) {
        this.pkSystemEnumId = pkSystemEnumId;
    }

    public Integer getSystemEnumNo() {
        return systemEnumNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_parameter.system_enum_no
     *
     * @param systemEnumNo the value for system_parameter.system_enum_no
     *
     * @mbggenerated Fri Dec 04 20:12:49 CST 2020
     */
    public void setSystemEnumNo(Integer systemEnumNo) {
        this.systemEnumNo = systemEnumNo;
    }

    public Long getConstant() {
        return constant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_parameter.constant
     *
     * @param constant the value for system_parameter.constant
     *
     * @mbggenerated Fri Dec 04 20:12:49 CST 2020
     */
    public void setConstant(Long constant) {
        this.constant = constant;
    }

    public String getKey() {
        return key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_parameter.key
     *
     * @param key the value for system_parameter.key
     *
     * @mbggenerated Fri Dec 04 20:12:49 CST 2020
     */
    public void setKey(String key) {
        this.key = key == null ? null : key.trim();
    }

    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_parameter.value
     *
     * @param value the value for system_parameter.value
     *
     * @mbggenerated Fri Dec 04 20:12:49 CST 2020
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }

    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_parameter.desc
     *
     * @param desc the value for system_parameter.desc
     *
     * @mbggenerated Fri Dec 04 20:12:49 CST 2020
     */
    public void setDesc(String desc) {
        this.desc = desc == null ? null : desc.trim();
    }

    public Long getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_parameter.sort
     *
     * @param sort the value for system_parameter.sort
     *
     * @mbggenerated Fri Dec 04 20:12:49 CST 2020
     */
    public void setSort(Long sort) {
        this.sort = sort;
    }

    public Long getCreateId() {
        return createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_parameter.create_id
     *
     * @param createId the value for system_parameter.create_id
     *
     * @mbggenerated Fri Dec 04 20:12:49 CST 2020
     */
    public void setCreateId(Long createId) {
        this.createId = createId;
    }

    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_parameter.create_time
     *
     * @param createTime the value for system_parameter.create_time
     *
     * @mbggenerated Fri Dec 04 20:12:49 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_parameter.update_time
     *
     * @param updateTime the value for system_parameter.update_time
     *
     * @mbggenerated Fri Dec 04 20:12:49 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public String getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_parameter.is_del
     *
     * @param isDel the value for system_parameter.is_del
     *
     * @mbggenerated Fri Dec 04 20:12:49 CST 2020
     */
    public void setIsDel(String isDel) {
        this.isDel = isDel == null ? null : isDel.trim();
    }
}